---
title: "Introduction to Admin Functions"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction to Admin Functions}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Summary 
The `rpactice` package provides a set of administrative functions for creating practice sets and for
auto-grading. These are intended for instructors and teaching assistents or anyone who would 
like to create a practice set of an assignment. 

The current administration functions for creating practice sets and for auto-grading are:

```
Function                        Purpose 
admin()                         List the admin functions.
admin.grade()                   Select a directory (dir) and grade all work.
admin.grade_file()              Select a file and grade it.
admin.grade_fn(fn)              Grade work in directory or grade single file.
admin.grade_repos(fn)           Grade a set of repos (fn/learner-dir/analysis.R)
admin.load(dir)                 Load practice sets from the directory.
admin.ls()                      List installed practice sets.
admin.prompts(short, show_a)    List the practice prompts
                                   show_a (TRUE|FALSE) show answers!
admin.run(short)                Execute the code in a practice set - and check if the code works.
```

# Grading Workflow
The basic grading workflow is as follows: 

## 1. Preparation
The completed assignments to be graded need to saved into a folder. Two basic organizations are supported. 
At the time of writing (Sept 30, 2022), I'm not sure which structure will be most effective.

**Organization 1: Flat file structure.** With this file organization, each 
assignment file (e.g., `analysis.R`) is given a unique name and all 
files are stored in a common directory. 
```
~/grading/A2/user_id1.R
~/grading/A2/user_id2.R
...
```
With this workflow, you would go to Canvas. Then, for each student in your lab section, you would go to 
their GitHub repository and copy and save their `analysis.R` file into `~/grading/A1/`.

**Organization 2: GitHub repo structure.** With this file structure, the entire GitHub Repo is cloned 
from GitHub. Here, it is assumed that the file to be graded is named `analysis.R`. 
```
~/grading/A1/git_hub_user1/analysis.R
~/grading/A1/git_hub_user2/analysis.R
...
```
There would, of course, be other files within each `git_hub-user` directory which would 
also be cloned. (I don't think it is possible to clone a single file.)

Organization 2 can be created by executing a sequence of `git clone` commands. For example, 
something like this:
```
git clone https://github.com/info201b-au2022/a1-git_hub_user1.git git_hub_user1
git clone https://github.com/info201b-au2022/a1-git_hub_user2.git git_hub_user2
...
git clone <repo_path> <dir_name>
```

**NOTE**: At the time of writing (Sept 30, 2022), I have not discovered an efficient way of cloning 
all repositories for students in a given lab section. I think the most effective way to 
do this is: 1) determine the GitHub user names from Canvas, 2) write a bash script with
clone commands for each of the GitHub user IDs, and 3) and then execute the bash script. 

## 2. Auto-grading
Once step #1 is completed and the files are saved on your computer, running the auto-grader
is straightforward.

The first step is to load the assignment markup file, which contains the answers. Let's
assume that the answers are located in this location: 
```
~/grading/markup/A2/answers.R
```
The `admin.load()` command will load all answer files from the directory:
```
library("rpractice")
admin.load("~/grading/markup/A2")
```

Now, you are ready to run the auto-grader. If all of your files are in one 
directory (Organization 1), run this command: 
```
library("rpractice")
admin_grade_fn("~/grading/A1")
```

If you have cloned repositories (Organization 2), run this command: 
```
library("rpractice")
admin.grade_repos("~/grading/A1/")
```

Running `admin.grade_repos("~/grading/A1/")` will generate the following terminal output: 
<font size="-20">
```
admin.grade_repos()
Student work: ~/grading/A01
Summary:
        Filename                     Name               Summary    Wrong Answers
[1]	user-1/analysis.R                Bill (user-1)      13 of 13                       
[2]	user-2/analysis.R                Sally (user-2)      0 of 13   1 2 3 4 5 6 7 8 9 10 12 13 14
[3]	user-3/analysis.R                Evan (user-3)       7 of 13   1 3 5 7 9 10   
See graded work in:
   ~/grading/A01/results/index.html
```
</font>
In this example, the assignments of three students have been graded. Reports on each 
of the assignments are found in the `results` directory. The `results` directory and 
reports are created by the grading process.

You can also grade a single file, as with these examples:
```
library("rpractice")
admin_grade_fn("~/grading/A1/user-1.R")
admin_grade_fn("~/grading/A1/user-3/analysis.R")
```

## 3. Reviewing 
The reports show which prompts were correct and incorrect, and the learners' code. These reports should 
allow you to move through the assignments quite efficiently and to grade the work in Canvas. 

## Creating and Testing Practice Sets
TBD

## 


